version: '3'

services:
  koin:
    image: koin
    ports:
      - 8080:8080
    depends_on:
      - redis
    env_file:
      - datas.env

  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    restart: always
    volumes:
      - redis

volumes:
  redis:
