version: '3'

services:
  koinkoin:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - redis
    env_file:
      - datas.env

  redis:
    build: ./redis
    restart: always
    volumes:
      - redis

volumes:
  redis:
