version: '3'

services:
  koinkoin:
    build: .
    ports:
      - 80:80
    depends_on:
      - redis
    env_file:
      - datas.env

  redis:
    build: ./redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis

volumes:
  redis:
